from backend.llm_client import chat_completion
from backend.logger import get_logger

logger = get_logger("medical_rag.answer")

MEDICAL_DISCLAIMER = """
⚕️ **Medical Disclaimer:** This information is generated by an AI system 
for educational and informational purposes only. It does not constitute 
medical advice, diagnosis, or treatment. Always consult a qualified 
healthcare professional for medical decisions.
"""


def generate_medical_answer(
    question: str,
    retrieved_chunks: list[dict],
    clinical_entities: dict = None,
    kb_context: dict = None,
) -> dict:
    """
    Generates a safe, cited medical answer.

    Context layers (richest possible context for accuracy):
    Layer 1 — Retrieved document chunks (primary source)
    Layer 2 — Clinical entities from Stage 2 (structured facts)
    Layer 3 — Knowledge base enrichment from Stage 3

    Always includes:
    - Source citations
    - Medical disclaimer
    - Critical value alerts
    - Confidence level
    """
    logger.info(
        f"Generating medical answer | "
        f"question='{question[:60]}' | "
        f"chunks={len(retrieved_chunks)}"
    )

    # Build document context from retrieved chunks
    doc_context_parts = []
    for i, chunk in enumerate(retrieved_chunks, 1):
        section = chunk.get("section", "document")
        score = chunk.get("retrieval_score", 0)
        doc_context_parts.append(
            f"[Source {i} — Section: {section} | Relevance: {score:.2f}]\n"
            f"{chunk['text']}"
        )
    doc_context = "\n\n".join(doc_context_parts)

    # Build clinical entity context from Stage 2
    entity_context = ""
    if clinical_entities:
        entities = clinical_entities.get("entities", {})
        parts = []

        if entities.get("diagnoses"):
            diag_names = [d.get("name") for d in entities["diagnoses"]]
            parts.append(f"Diagnosed conditions: {', '.join(diag_names)}")

        if entities.get("medications"):
            med_names = [
                f"{m.get('name')} {m.get('dosage', '')}".strip()
                for m in entities["medications"]
            ]
            parts.append(f"Current medications: {', '.join(med_names)}")

        if entities.get("lab_values"):
            abnormal_labs = [
                l for l in entities["lab_values"]
                if l.get("interpretation") not in ["normal", "unknown"]
            ]
            if abnormal_labs:
                lab_strs = [
                    f"{l.get('test_name')}: {l.get('value')} "
                    f"({l.get('interpretation', 'unknown')})"
                    for l in abnormal_labs
                ]
                parts.append(f"Abnormal labs: {', '.join(lab_strs)}")

        if parts:
            entity_context = (
                "\n=== EXTRACTED CLINICAL ENTITIES ===\n" +
                "\n".join(parts)
            )

    # Build KB context from Stage 3
    kb_summary = ""
    if kb_context:
        summary = kb_context.get("clinical_summary", {})
        if summary:
            triage = summary.get("triage_level", "routine")
            monitoring = summary.get("monitoring_requirements", [])[:5]
            gaps = summary.get("treatment_gaps", [])

            kb_parts = [f"Triage level: {triage}"]
            if monitoring:
                kb_parts.append(
                    f"Monitoring needed: {', '.join(monitoring[:3])}"
                )
            if gaps:
                conditions = [g.get("condition") for g in gaps]
                kb_parts.append(
                    f"Potential treatment gaps for: {', '.join(conditions)}"
                )

            kb_summary = (
                "\n=== KNOWLEDGE BASE CONTEXT ===\n" +
                "\n".join(kb_parts)
            )

    # Build the complete prompt
    system_prompt = """You are a clinical decision support AI assistant.
Your role is to help healthcare professionals by analyzing medical documents.

CRITICAL RULES:
1. Base answers ONLY on provided context — never fabricate medical information
2. Always cite sources using [Source N] notation
3. Clearly distinguish between confirmed findings and possibilities
4. Flag critical/abnormal values prominently
5. Never make definitive diagnoses — use language like "the document indicates" or "findings suggest"
6. Recommend professional consultation for clinical decisions
7. If information is not in the context, explicitly say so"""

    user_prompt = f"""Medical Question: {question}

=== DOCUMENT CONTEXT ===
{doc_context}
{entity_context}
{kb_summary}

Please provide a comprehensive, clinically accurate answer that:
1. Directly answers the question using the document context
2. Cites specific sources [Source N] for key facts
3. Highlights any critical or abnormal findings
4. Notes any important clinical considerations
5. Ends with relevant follow-up recommendations"""

    logger.info("Calling MiniMax for medical answer generation")

    answer_text = chat_completion(
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        max_tokens=1500,
        temperature=0.1,
    )

    # Detect critical findings in retrieved content
    critical_alerts = _detect_critical_findings(
        retrieved_chunks, clinical_entities
    )

    # Build sources list
    sources = [
        {
            "source_number": i + 1,
            "section": chunk.get("section", "unknown"),
            "chunk_type": chunk.get("chunk_type", "unknown"),
            "relevance_score": chunk.get("retrieval_score", 0),
            "text_preview": chunk["text"][:150] + "...",
        }
        for i, chunk in enumerate(retrieved_chunks)
    ]

    logger.info(
        f"Answer generated | "
        f"chars={len(answer_text)} | "
        f"critical_alerts={len(critical_alerts)}"
    )

    return {
        "answer": answer_text,
        "disclaimer": MEDICAL_DISCLAIMER.strip(),
        "sources": sources,
        "critical_alerts": critical_alerts,
        "chunks_used": len(retrieved_chunks),
    }


def _detect_critical_findings(
    chunks: list[dict],
    clinical_entities: dict = None,
) -> list[dict]:
    """
    Scans retrieved chunks and clinical entities for critical findings
    that should be prominently flagged to the clinician.
    """
    alerts = []

    # Check lab values for critical results
    if clinical_entities:
        for lab in clinical_entities.get(
            "entities", {}
        ).get("lab_values", []):
            if "critical" in str(lab.get("interpretation", "")):
                alerts.append({
                    "type": "critical_lab_value",
                    "severity": "high",
                    "finding": (
                        f"{lab.get('test_name')}: "
                        f"{lab.get('value')} {lab.get('unit', '')} — "
                        f"CRITICAL ({lab.get('interpretation')})"
                    ),
                })

    # Check chunks for critical keywords
    critical_keywords = [
        "critical", "stat", "emergency", "urgent",
        "immediately", "life-threatening", "cardiac arrest",
        "respiratory failure", "septic shock"
    ]

    for chunk in chunks:
        text_lower = chunk["text"].lower()
        for keyword in critical_keywords:
            if keyword in text_lower:
                alerts.append({
                    "type": "critical_keyword",
                    "severity": "high",
                    "finding": (
                        f"Critical keyword '{keyword}' found in "
                        f"section: {chunk.get('section', 'unknown')}"
                    ),
                })
                break

    return alerts