import json
from backend.llm_client import chat_completion_json, chat_completion
from backend.logger import get_logger

logger = get_logger("clinical_agents.safety")

MANDATORY_DISCLAIMER = """
⚕️ IMPORTANT MEDICAL DISCLAIMER: This clinical assessment is 
generated by an AI system for decision support purposes only. 
It does not constitute medical advice, diagnosis, or treatment. 
All clinical decisions must be made by licensed healthcare 
professionals. In case of emergency, contact emergency services immediately.
"""


def safety_agent(state: dict) -> dict:
    """
    Agent 5 — Safety & Ethics Agent

    Quality controller and final reviewer. Reads ALL other
    agents' outputs and ensures the combined assessment is:
    - Safe (no dangerous advice)
    - Ethical (appropriate disclaimers)
    - Complete (all key findings addressed)
    - Accurate (consistent across agents)

    Can approve, request revision, or escalate.

    Reads:  ALL previous agent outputs
    Writes: safety_report, safety_approved, final_answer
    """
    document_id = state["document_id"]
    question = state["patient_question"]
    urgency = state.get("urgency_level", "routine")
    is_emergency = state.get("is_emergency", False)
    iteration = state.get("iterations", 1)

    logger.info(
        f"Safety Agent | doc_id={document_id} | "
        f"urgency={urgency} | iter={iteration}"
    )

    triage_report = state.get("triage_report", "Not available")
    diagnosis_report = state.get("diagnosis_report", "Not available")
    pharmacist_report = state.get("pharmacist_report", "Not available")
    research_findings = state.get("research_findings", "Not available")
    drug_alerts = state.get("drug_alerts", [])
    medication_safe = state.get("medication_safe", True)
    primary_diagnosis = state.get("primary_diagnosis", "")

    # Build safety review context
    major_alerts = [
        a for a in drug_alerts if a.get("severity") == "major"
    ]

    safety_prompt = f"""You are a patient safety officer and medical ethics specialist.
Review this multi-agent clinical assessment for safety, completeness, and ethical compliance.

QUESTION: {question}
URGENCY: {urgency.upper()}
IS EMERGENCY: {is_emergency}
PRIMARY DIAGNOSIS: {primary_diagnosis}
MEDICATION SAFE: {medication_safe}
MAJOR DRUG ALERTS: {len(major_alerts)}

TRIAGE REPORT:
{triage_report[:300]}

DIAGNOSIS REPORT:
{diagnosis_report[:300]}

PHARMACIST REPORT:
{pharmacist_report[:300]}

RESEARCH FINDINGS:
{research_findings[:300]}

Evaluate and return ONLY valid JSON:
{{
    "safety_approved": true | false,
    "overall_safety_rating": "safe" | "caution" | "unsafe",
    "safety_concerns": ["concern 1", "concern 2"],
    "revision_needed": true | false,
    "revision_target": "triage" | "diagnosis" | "pharmacist" | "research" | null,
    "revision_reason": "specific reason if revision needed",
    "completeness_score": 1-10,
    "accuracy_assessment": "assessment of consistency across agents",
    "emergency_actions": ["action if emergency"] | [],
    "key_safety_points": ["safety point 1", "safety point 2"]
}}

Approve if: comprehensive, consistent, safe, no dangerous advice
Reject if: dangerous advice present, major inconsistencies, critical omissions"""

    try:
        raw = chat_completion_json(
            messages=[
                {
                    "role": "system",
                    "content": "You are a patient safety officer. Return valid JSON only."
                },
                {"role": "user", "content": safety_prompt}
            ],
            max_tokens=512,
        )

        cleaned = raw.strip()
        if "```" in cleaned:
            cleaned = cleaned.split("```")[1]
            if cleaned.startswith("json"):
                cleaned = cleaned[4:]

        safety_result = json.loads(cleaned.strip())

        approved = safety_result.get("safety_approved", True)
        revision_needed = (
            safety_result.get("revision_needed", False) and
            iteration < state.get("max_iterations", 3)
        )

        safety_concerns = safety_result.get("safety_concerns", [])
        if major_alerts:
            safety_concerns.insert(
                0,
                f"{len(major_alerts)} major drug interaction(s) identified"
            )

        safety_report = f"""=== SAFETY & ETHICS REVIEW ===
Overall Safety Rating: {safety_result.get('overall_safety_rating','').upper()}
Completeness Score: {safety_result.get('completeness_score',7)}/10
Approved: {'YES ✅' if approved else 'PENDING REVISION ⚠️'}

Safety Concerns:
{chr(10).join(f"- {c}" for c in safety_concerns) or "None identified"}

Key Safety Points:
{chr(10).join(f"- {p}" for p in safety_result.get('key_safety_points',[])[:5])}

Accuracy Assessment: {safety_result.get('accuracy_assessment','')}"""

        # If approved or max iterations reached, compile final answer
        final_answer = ""
        if approved or not revision_needed:
            final_answer = _compile_final_answer(
                state, safety_result, MANDATORY_DISCLAIMER
            )

        logger.info(
            f"Safety Agent complete | "
            f"approved={approved} | "
            f"revision={revision_needed} | "
            f"concerns={len(safety_concerns)}"
        )

        return {
            "safety_report": safety_report,
            "safety_approved": approved,
            "safety_concerns": safety_concerns,
            "revision_needed": revision_needed,
            "revision_target": safety_result.get("revision_target", ""),
            "final_answer": final_answer,
            "iterations": iteration + 1,
            "agent_messages": [{
                "agent": "Safety",
                "iteration": iteration,
                "approved": approved,
                "rating": safety_result.get("overall_safety_rating"),
                "concerns": len(safety_concerns),
                "revision_needed": revision_needed,
            }],
        }

    except Exception as e:
        logger.error(f"Safety agent failed: {e}", exc_info=True)
        final_answer = _compile_final_answer(
            state, {}, MANDATORY_DISCLAIMER
        )
        return {
            "safety_report": "Safety review encountered an error — defaulting to approved with caution.",
            "safety_approved": True,
            "safety_concerns": ["Safety review system error — manual review recommended"],
            "revision_needed": False,
            "revision_target": "",
            "final_answer": final_answer,
            "iterations": iteration + 1,
            "agent_messages": [{
                "agent": "Safety",
                "iteration": iteration,
                "error": str(e),
            }],
        }


def _compile_final_answer(
    state: dict,
    safety_result: dict,
    disclaimer: str,
) -> str:
    """
    Compiles all agent reports into a final comprehensive
    clinical assessment document.
    """
    urgency = state.get("urgency_level", "routine")
    primary = state.get("primary_diagnosis", "")
    evidence = state.get("evidence_level", "C")
    triage_alerts = state.get("triage_alerts", [])
    drug_alerts = state.get("drug_alerts", [])
    safety_concerns = safety_result.get("safety_concerns", [])
    emergency_actions = safety_result.get("emergency_actions", [])

    sections = [
        f"# CLINICAL ASSESSMENT REPORT",
        f"Urgency Level: {urgency.upper()}",
        f"Primary Diagnosis: {primary or 'Under investigation'}",
        f"Evidence Level: {evidence}",
        "",
    ]

    if emergency_actions:
        sections += [
            "## 🚨 EMERGENCY ACTIONS REQUIRED",
            "\n".join(f"- {a}" for a in emergency_actions),
            "",
        ]

    if triage_alerts:
        sections += [
            "## ⚠️ TRIAGE ALERTS",
            "\n".join(f"- {a}" for a in triage_alerts[:3]),
            "",
        ]

    if drug_alerts:
        major_alerts = [
            a for a in drug_alerts if a.get("severity") == "major"
        ]
        if major_alerts:
            sections += [
                "## 🔴 MAJOR DRUG INTERACTION ALERTS",
                "\n".join([
                    f"- {a.get('drugs','')}: {a.get('effect','')[:80]}"
                    for a in major_alerts
                ]),
                "",
            ]

    sections += [
        "## CLINICAL FINDINGS",
        state.get("diagnosis_report", "")[:600] or "Not available",
        "",
        "## MEDICATION SAFETY",
        state.get("pharmacist_report", "")[:400] or "Not available",
        "",
        "## RESEARCH EVIDENCE",
        state.get("research_findings", "")[:400] or "Not available",
        "",
    ]

    if safety_concerns:
        sections += [
            "## SAFETY NOTES",
            "\n".join(f"- {c}" for c in safety_concerns[:3]),
            "",
        ]

    sections.append(disclaimer.strip())

    return "\n".join(sections)